server:
  port: 8080
  mode: debug
  read_timeout: 60s
  write_timeout: 60s

database:
  postgres:
    host: localhost
    port: 5432
    user: catisip
    password: catisip123
    dbname: catisip
    sslmode: disable
    max_open_conns: 100
    max_idle_conns: 10
    conn_max_lifetime: 1h
  
  redis:
    host: localhost
    port: 6379
    password: ""
    db: 0
    pool_size: 10

freeswitch:
  host: localhost
  port: "8021"
  password: ClueCon
  max_connections: 10
  reconnect_delay: 5s
  outbound_port: "18086"

jwt:
  secret: catisip_jwt_secret_key_2025
  expire_hours: 24
  refresh_expire_hours: 168

log:
  level: debug
  format: json
  output: stdout
  file_path: /var/log/catisip/app.log

cors:
  allow_origins:
    - http://localhost:3000
    - http://localhost:3001
    - http://localhost:3002
  allow_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allow_headers:
    - Content-Type
    - Authorization

websocket:
  read_buffer_size: 1024
  write_buffer_size: 1024
  heartbeat_interval: 30s
  message_queue_size: 100
